repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.5
    hooks:
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]