name: apollo

services:
  postgres:
    container_name: apollo_postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: apollo
      POSTGRES_PASSWORD: apollo
      POSTGRES_DB: apollo
    ports:
      - 5432:5432
    volumes:
      - postgres_data_container:/var/lib/postgresql/data

  influxdb:
    container_name: apollo_influxdb
    image: influxdb:latest
    restart: unless-stopped
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: apollo
      DOCKER_INFLUXDB_INIT_PASSWORD: apollo
      DOCKER_INFLUXDB_INIT_ORG: apollo
      DOCKER_INFLUXDB_INIT_BUCKET: prices
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data_container:/var/lib/influxdb2

volumes:
  postgres_data_container:
  influxdb_data_container: