[tool.poetry]
name = "apollo"
version = "0.1.0"
description = "Research & Development of trading strategies"
authors = ["Stan <stanis.konnov@gmail.com>"]
packages = [
  { include = "apollo", from = "src" }
]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
pandas = "^1.5.3"
numpy = "^1.24.2"
jupyter = "^1.0.0"
scipy = "^1.3.0"
plotly = "^5.14.0"
python-dotenv = "^1.0.0"
backtesting = "^0.3.3"
yfinance = "^0.2.37"
tqdm = "^4.66.2"
pytest = "^8.1.1"
pytest-cov = "^5.0.0"
poethepoet = "^0.25.1"
scikit-learn = "^1.4.2"
statsmodels = "^0.14.2"
ruff = "^0.4.5"
pre-commit = "^3.7.1"

[tool.poetry.dev-dependencies]

[tool.coverage.run]
omit = [
  "*/__init__.py",
  "*/settings.py",
  "*/commands/*",
  "*/types.py",
  "*/tests/*",
]

[tool.poe.tasks]
test = "pytest -v --cov=src --cov-report term-missing"

optimize = "python3 src/apollo/commands/optimize.py"
backtest = "python3 src/apollo/commands/backtest.py"
experiment = "python3 src/apollo/commands/experiment.py"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
