[tool.poetry]
name = "apollo"
version = "0.1.0"
description = "Analyzes price data of provided tickers to identify trade signals by using technical indicators"
authors = ["Stan <stanis.konnov@gmail.com>"]
packages = [
  { include = "apollo", from = "src" }
]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
pandas = "^1.5.3"
numpy = "^1.24.2"
jupyter = "^1.0.0"
mplfinance = "^0.12.9b7"
scipy = "^1.3.0"
scikit-learn = "^1.2.2"
plotly = "^5.14.0"
requests = "^2.31.0"
python-dotenv = "^1.0.0"
arrow = "^1.2.3"

# Please leave me pinned
kaleido = "0.2.1"
pymongo = "^4.3.3"
asyncio = "^3.4.3"
backtesting = "^0.3.3"
yfinance = "^0.2.37"
tqdm = "^4.66.2"
pytest = "^8.1.1"
pytest-cov = "^5.0.0"

[tool.poetry.dev-dependencies]

[tool.coverage.run]
omit = [
    "*/__init__.py",
    "*/settings.py",
    "*/tests/*",
    ]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
